### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by neuthral** [miguelmota/ipdr#1]
`go install https://github.com/miguelmota/ipdr/cmd/ipdr                                       
can't load package: package https:/github.com/miguelmota/ipdr/cmd/ipdr: cannot find package "https:/github.com/miguelmota/ipdr/cmd/ipdr" in any of:
	/usr/lib/go-1.10/src/https:/github.com/miguelmota/ipdr/cmd/ipdr (from $GOROOT)
	/home/bender/.go/src/https:/github.com/miguelmota/ipdr/cmd/ipdr (from $GOPATH)
`

**Comment by miguelmota** [comment]
@neuthral 

try

```bash
go get -u github.com/miguelmota/ipdr/cmd/ipdr
```

**Comment by miguelmota** [comment]
please reopen issue if still having problems. The install instructions have been updated. Thanks for reporting.
