### ISSUE TITLE
ipdr push always fail (Help wanted)

### ISSUE THREAD

**Issue by liangliu-lab** [miguelmota/ipdr#10]
Hi, 
I am using the latest ipdr sw, and trying to push the image to ipfs, while not working and pending, here is the output:

API server listening at: 127.0.0.1:12641
time="2020-11-11T15:15:14+08:00" level=info msg="[registry] temp: /tmp/933118882"
time="2020-11-11T15:15:14+08:00" level=info msg="[registry] preparing image in: /tmp/021345433"
time="2020-11-11T15:15:14+08:00" level=info msg="\n[registry] dist: /tmp/021345433/default/blobs/sha256:fe85b92a230037eeda1b552cd0d586ac1c345ee4dd2ba0e3028d837ec7cdae36"
time="2020-11-11T15:15:14+08:00" level=info msg="[registry] compressing layer: /tmp/933118882/3843b7e213befd47012d01d57cd13733844715869205b5edcc4d6d91c399574e/layer.tar"
time="2020-11-11T15:15:14+08:00" level=info msg="[registry] root dir: /tmp/021345433"
time="2020-11-11T15:15:14+08:00" level=info msg="[registry] upload hash QmS7C9TMHPph5uaCNhFVSz2Dw83RYuNsz1p3BC6hvbnBpw"

So,  I entered the debug, and found it stops here in register.go file,
**_firstRef = <-refs_**
Looks the channel was blocking,  could you help checking here what's happening?  Thank a lot in advance, 

Here are more logs:
xxxxx@xxxxx:~$ ipfs daemon
Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4
Swarm is limited to private network of peers with the swarm key
Swarm key fingerprint: 3c677552a00bc73dd84197e7e32a57fe
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.111/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.111/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

**Comment by liangliu-lab** [comment]
Hi, the image push to IPFS is working now, thank you Li Qiang!

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/ipdr/pull/11
