### ISSUE TITLE
IPDR false pulling image

### ISSUE THREAD

**Issue by liangliu-lab** [miguelmota/ipdr#13]
Hi,  two scenarios,  1st always succeeds, 2nd actually false downloading
1.  If local docker environment already has one image with the same image id as the one to download from IPFS, this will succeed, because the downloading process actually will tag the image as from IPFS, like _docker.localhost:5000/ciqpszt6znuub2lsjf4svnzewe4xjsrtwxhs57dkhp4j4zy2nm7nvpi_
2.  If local docker environment does not have ,  the image downloading actually has no output (you can check by docker image ls), even if _**ipdr pull**_ commands output show it successfully done.

**Comment by liangliu-lab** [comment]
Hi, 
1. When the image uploaded from docker, it was split into several blobs by the ipfs file management mechanism,  as in the attached picture. 
![image](https://user-images.githubusercontent.com/68547299/101466840-8f6dd580-397c-11eb-9ec8-3d362a2624e5.png)

2. While when the image requested to be downloaded into the other docker client,  the docker  engine may not know how to assemble them back to form an image. Is it possible the reason?  Here attached the docker demon output logs?
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.770574390+08:00" level=debug msg="Calling HEAD /_ping"
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.782784004+08:00" level=debug msg="Calling POST /v1.40/images/create?fromImage=docker.localhost%3A5000%2Fciqpszt6znuub2lsjf4svnzewe4xjsrtwxhs57dkhp4j4zy2nm7nvpi&tag=latest"
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.783067654+08:00" level=debug msg="Trying to pull docker.localhost:5000/ciqpszt6znuub2lsjf4svnzewe4xjsrtwxhs57dkhp4j4zy2nm7nvpi from https://docker.localhost:5000 v2"
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.783678582+08:00" level=warning msg="Error getting v2 registry: Get https://docker.localhost:5000/v2/: http: server gave HTTP response to HTTPS client"
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.783695980+08:00" level=info msg="Attempting next endpoint for pull after error: Get https://docker.localhost:5000/v2/: http: server gave HTTP response to HTTPS client"
Dec  8 16:22:59 xxxx  dockerd[13496]: time="2020-12-08T16:22:59.783723531+08:00" level=debug msg="Trying to pull docker.localhost:5000/ciqpszt6znuub2lsjf4svnzewe4xjsrtwxhs57dkhp4j4zy2nm7nvpi from http://docker.localhost:5000 v2"
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.790512373+08:00" level=debug msg="Pulling ref from V2 registry: docker.localhost:5000/ciqpszt6znuub2lsjf4svnzewe4xjsrtwxhs57dkhp4j4zy2nm7nvpi:latest"
Dec  8 16:22:59 xxxx  dockerd[13496]: time="2020-12-08T16:22:59.790696091+08:00" level=debug msg="pulling blob \"sha256:bb79b6b2107fea8e8a47133a660b78e3a546998fcf0427be39ac9a0af4a97e90\""
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.790744807+08:00" level=debug msg="pulling blob \"sha256:5a9f1c0027a73bc0e66a469f90e47a59e23ab3472126ed28e6a4e7b1a98d1eb5\""
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.790818554+08:00" level=debug msg="pulling blob \"sha256:b5c20b2b484f5ca9bc9d98dc79f8f1381ee0c063111ea0ddf42d1ae5ea942d50\""
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.807338839+08:00" level=error msg="filesystem layer verification failed for digest sha256:b5c20b2b484f5ca9bc9d98dc79f8f1381ee0c063111ea0ddf42d1ae5ea942d50"
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.807360047+08:00" level=error msg="Download failed: filesystem layer verification failed for digest sha256:b5c20b2b484f5ca9bc9d98dc79f8f1381ee0c063111ea0ddf42d1ae5ea942d50"
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.826507853+08:00" level=error msg="image config verification failed for digest sha256:c39a868aad02a383c7e490e0fc4a5b0217f667f2de764bc2755e315a5adf64a1"
Dec  8 16:22:59 xxxx dockerd[13496]: time="2020-12-08T16:22:59.826539655+08:00" level=error msg="Not continuing with pull after error: error pulling image configuration: image config verification failed for digest sha256:c39a868aad02a383c7e490e0fc4a5b0217f667f2de764bc2755e315a5adf64a1"

**Comment by liangliu-lab** [comment]
Hi，great done !
Can we manage to combine this commit?  These are bit complex changes.
BR/LL.

**Comment by liangliu-lab** [comment]
Hi,
The patches verified working, ~~ thumb ~~
BR/LL

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/ipdr/pull/14
